/* FINAL KNOWLEDGE CHECK — 4 shared + 6 role-specific = 10 per learner, wording tailored by function */
(function () {
  const V = window.CV;
  window.COURSE.finalCheck.questions.push(
    { id: "s1", track: "all",
      q: V({ ops: "Smart Queue went live two weeks ago and training is complete, but half the team still works from a personal list. What does this tell you?", sup: "The portal went live two weeks ago and training is complete, but half the requests still arrive by email. What does this tell you?" }),
      options: ["The change failed.", "The change event is complete; the human transition isn't.", "Disciplinary action is needed.", "The workaround should become the standard."],
      answer: 1, explain: "Launch and training show the event happened. Adoption depends on the transition, which takes longer and needs support and reinforcement." },
    { id: "s2", track: "all",
      q: V({ ops: "Someone supports the change but can't get time to practice during peak volume. What type of pushback is this?", sup: "Someone supports the change but can't get time to practice during month-end peaks. What type of pushback is this?" }),
      options: ["Information gap", "Design feedback", "Capability gap", "Accountability issue"],
      answer: 2, explain: "Supportive but lacking practice, time, skill, or access is a capability gap. Remove the barrier." },
    { id: "s3", track: "all",
      q: V({ tl: "In a team meeting across two shifts, nobody asks questions after you explain a change. What should you conclude?", mgr: "In a leadership meeting across several sites, none of your Team Leaders asks questions after you explain a change. What should you conclude?" }),
      options: ["Everyone understood and agrees.", "Silence isn't necessarily agreement. Check understanding by asking people to explain it in their own words, and offer other channels for questions.", "The group is disengaged.", "The message was too long."],
      answer: 1, explain: "Silence can mean processing, politeness, or confusion. Check through explanation, and offer more than one channel." },
    { id: "s4", track: "all",
      q: "Which phrase best handles a valid concern without encouraging a workaround?",
      options: ["“You're right; this won't work.”", V({ ops: "“That's a valid risk to investigate. Please log the example in the issue log while we keep following the approved workflow.”", sup: "“That's a valid risk to investigate. Please log the example in the issue tracker while we keep following the approved process.”" }), "“Just do it.”", "“Everyone hates change.”"],
      answer: 1, explain: "Validate the risk, route the evidence, and keep the approved process in place." },

    { id: "t1", track: "tl",
      q: V({ ops: "A trained specialist can explain the new queue logic but can't work it at normal volume. What's the likely barrier?", sup: "A trained coordinator can explain the portal categories but can't keep up at normal volume. What's the likely barrier?" }),
      options: ["Awareness", "Desire", "Knowledge", "Ability"],
      answer: 3, explain: "Ability: they know it but can't yet do it reliably in real conditions. Provide realistic practice, observation, feedback, and barrier removal." },
    { id: "t2", track: "tl",
      q: "A Team Leader says, “Don't ask questions; the decision is final.” Which SCARF domains are most threatened?",
      options: ["Relatedness only", "Autonomy and Certainty, and potentially Status and Fairness", "Status only", "None"],
      answer: 1, explain: "Removing voice threatens Autonomy; refusing questions leaves Certainty gaps; dismissal can feel like a Status and Fairness threat." },
    { id: "t3", track: "tl",
      q: "When is an accountability response appropriate?",
      options: ["When someone disagrees publicly.", "When expectations and rationale are clear, access and support are available, ability has been demonstrated, and the behavior still isn't followed.", "As soon as performance drops.", "When your manager asks for it."],
      answer: 1, explain: "Accountability follows enablement and evidence, never before." },
    { id: "t4", track: "tl",
      q: "In the 5L conversation, what does the Lock step require?",
      options: ["Ending the conversation politely.", "Agreeing on action, owner, date, measure, and follow-up.", "Restating the policy firmly.", "Escalating to your manager."],
      answer: 1, explain: "Lock turns the conversation into checkable commitments: who does what, by when, measured how, and when you'll follow up." },
    { id: "t5", track: "tl",
      q: V({ ops: "What's the first step before challenging an RCM workflow?", sup: "What's the first step before challenging a support process?" }),
      options: ["Try the new method quietly.", "Define the problem with evidence and identify the governance and safeguards needed before testing.", "Ask the team to vote.", "Update the job aid."],
      answer: 1, explain: V({ ops: "Evidence and governance come first, so improvement never bypasses compliance, privacy, or client requirements.", sup: "Evidence and governance come first, so improvement never bypasses security, privacy, or audit requirements." }) },
    { id: "t6", track: "tl",
      q: V({ ops: "Newer specialists accept every AI recommendation without reviewing the account. What's the best response?", sup: "Newer coordinators accept every AI triage suggestion without checking the request. What's the best response?" }),
      options: ["Praise their speed.", "Use contrasting examples, and require a reason before accepting or overriding a suggestion.", "Turn the feature off.", "Tell them to trust their instincts."],
      answer: 1, explain: "Over-reliance is a Knowledge and Ability gap. Requiring a reason keeps human accountability in place." },

    { id: "m1", track: "mgr",
      q: V({ ops: "Training completion is 100%, but legacy work list use remains high. What does this show?", sup: "Training completion is 100%, but a third of requests still bypass the portal. What does this show?" }),
      options: ["The change succeeded.", "Activity is complete, but adoption isn't. Diagnose the barriers and operating conditions.", "Training must be repeated.", "People are resistant."],
      answer: 1, explain: "Training shows exposure, not adoption. Find what in the system still rewards the old way." },
    { id: "m2", track: "mgr",
      q: "Which is a sponsor action rather than sponsor messaging?",
      options: ["An endorsement email", "Allocating resources, resolving priority conflicts, making decisions, removing barriers, and holding leaders accountable", "An upbeat town hall opening", "An intranet article"],
      answer: 1, explain: "Sponsorship shows in decisions and resources; messaging alone asks people to change while the system stays the same." },
    { id: "m3", track: "mgr",
      q: V({ ops: "Why break adoption data down by site, shift, and access?", sup: "Why break adoption data down by team, request type, and requesting department?" }),
      options: ["To rank individuals.", "Averages can hide unequal access, local barriers, shift differences, or capability gaps.", "To make reports longer.", "For audit purposes only."],
      answer: 1, explain: "Breaking data down reveals the uneven conditions that averages hide." },
    { id: "m4", track: "mgr",
      q: "What makes an early win credible?",
      options: ["It's announced quickly.", "It's verified, relevant to stakeholders, linked to the change, and doesn't hide guardrail problems.", "The sponsor likes it.", "It shows the biggest percentage improvement."],
      answer: 1, explain: "An unverified win, or one hiding a guardrail failure, damages credibility when the truth surfaces." },
    { id: "m5", track: "mgr",
      q: "When should a Manager pause or contain part of a change?",
      options: ["When complaints increase.", V({ ops: "When defined risk thresholds are breached or governance requires review, especially for compliance, privacy, security, patient, client, or material financial risk.", sup: "When defined risk thresholds are breached or governance requires review, especially for security, privacy, legal, payroll, or audit risk." }), "Only with sponsor approval.", "Never."],
      answer: 1, explain: "Containment is triggered by risk thresholds and governance, not by complaint volume." },
    { id: "m6", track: "mgr",
      q: V({ ops: "The VP asks you to launch a significant new initiative for teams already absorbing two others. What's the correct principle?", sup: "The COO asks you to launch a significant new initiative for teams already absorbing two others. What's the correct principle?" }),
      options: ["Teams can absorb it if motivated.", "Never add significant change without naming where the capacity comes from: what will be stopped, paused, sequenced, or resourced.", "Launch it and monitor fatigue.", "Delay telling the teams."],
      answer: 1, explain: "“Absorb it” isn't a capacity plan. Make the trade-off explicit." }
  );
})();
